# Generated by Django 3.0.8 on 2020-07-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_customess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectricConsumption',
        ),
        migrations.DeleteModel(
            name='TouMatrix',
        ),
    ]
