# Generated by Django 3.0.8 on 2020-07-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200716_0920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomESS',
        ),
    ]
